
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import javax.swing.JButton;

/**
 * JCalc: A Simple calculator
 * 
 */

public class JCalc extends javax.swing.JFrame{

    /**
     * Run the calculator from the command line
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JCalc JCalc = new JCalc();
                JCalc.setLocationRelativeTo(null);
                JCalc.setVisible(true);
            }
        });
    }

    /**
     * Creates new form JCalc
     */
    public JCalc() {
        initComponents();
        clear();
        display.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        displayPanel = new javax.swing.JPanel();
        display = new javax.swing.JLabel()
        {
            public java.awt.Dimension getMaximumSize()
            {
                return new java.awt.Dimension(1000, 30);
            }
        }
        ;
        mainPanel = new javax.swing.JPanel();
        rowPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ce = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        plusminus = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        rowPanel2 = new javax.swing.JPanel();
        digit9 = new javax.swing.JButton();
        digit8 = new javax.swing.JButton();
        digit7 = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        rowPanel3 = new javax.swing.JPanel();
        digit4 = new javax.swing.JButton();
        digit5 = new javax.swing.JButton();
        digit6 = new javax.swing.JButton();
        times = new javax.swing.JButton();
        rowPanel4 = new javax.swing.JPanel();
        digit1 = new javax.swing.JButton();
        digit2 = new javax.swing.JButton();
        digit3 = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        rowPanel5 = new javax.swing.JPanel();
        digit0 = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        plus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCalc");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("jCalc"); // NOI18N
        setPreferredSize(new java.awt.Dimension(260, 350));
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentResized(java.awt.event.ComponentEvent evt)
            {
                formComponentResized(evt);
            }
        });

        displayPanel.setBackground(new java.awt.Color(0, 0, 0));
        displayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        displayPanel.setMaximumSize(new java.awt.Dimension(400, 400));
        displayPanel.setMinimumSize(new java.awt.Dimension(51, 69));
        displayPanel.setOpaque(false);
        displayPanel.setPreferredSize(new java.awt.Dimension(75, 100));
        displayPanel.setLayout(new java.awt.GridLayout());

        display.setBackground(new java.awt.Color(204, 204, 204));
        display.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("0");
        display.setAlignmentX(0.5F);
        display.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        display.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        display.setMaximumSize(null);
        display.setMinimumSize(null);
        display.setOpaque(true);
        display.setPreferredSize(new java.awt.Dimension(100, 200));
        displayPanel.add(display);

        getContentPane().add(displayPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        mainPanel.setLayout(new java.awt.GridLayout(5, 0, 0, 4));

        rowPanel1.setBackground(new java.awt.Color(0, 0, 0));
        rowPanel1.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        ce.setBackground(new java.awt.Color(102, 102, 102));
        ce.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ce.setForeground(new java.awt.Color(255, 255, 255));
        ce.setText("CE");
        ce.setBorder(null);
        ce.setPreferredSize(new java.awt.Dimension(0, 20));
        ce.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                ceActionPerformed(evt);
            }
        });
        jPanel1.add(ce);

        rowPanel1.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        plusminus.setBackground(new java.awt.Color(102, 102, 102));
        plusminus.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        plusminus.setForeground(new java.awt.Color(255, 255, 255));
        plusminus.setText("+/-");
        plusminus.setBorder(null);
        plusminus.setPreferredSize(new java.awt.Dimension(0, 20));
        plusminus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                plusminusActionPerformed(evt);
            }
        });
        jPanel2.add(plusminus);

        percent.setBackground(new java.awt.Color(102, 102, 102));
        percent.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        percent.setForeground(new java.awt.Color(255, 255, 255));
        percent.setText("%");
        percent.setBorder(null);
        percent.setPreferredSize(new java.awt.Dimension(0, 20));
        percent.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                percentActionPerformed(evt);
            }
        });
        jPanel2.add(percent);

        rowPanel1.add(jPanel2);

        mainPanel.add(rowPanel1);

        rowPanel2.setBackground(new java.awt.Color(0, 0, 0));
        rowPanel2.setPreferredSize(new java.awt.Dimension(250, 31));
        rowPanel2.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        digit9.setBackground(new java.awt.Color(102, 102, 102));
        digit9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit9.setForeground(new java.awt.Color(255, 255, 255));
        digit9.setText("9");
        digit9.setBorder(null);
        digit9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel2.add(digit9);

        digit8.setBackground(new java.awt.Color(102, 102, 102));
        digit8.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit8.setForeground(new java.awt.Color(255, 255, 255));
        digit8.setText("8");
        digit8.setBorder(null);
        digit8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        digit8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel2.add(digit8);

        digit7.setBackground(new java.awt.Color(102, 102, 102));
        digit7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit7.setForeground(new java.awt.Color(255, 255, 255));
        digit7.setText("7");
        digit7.setBorder(null);
        digit7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel2.add(digit7);

        divide.setBackground(new java.awt.Color(102, 102, 102));
        divide.setForeground(new java.awt.Color(255, 255, 255));
        divide.setText("/");
        divide.setBorder(null);
        divide.setMaximumSize(new java.awt.Dimension(75, 31));
        divide.setMinimumSize(new java.awt.Dimension(75, 31));
        divide.setPreferredSize(new java.awt.Dimension(75, 31));
        divide.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opActionPerformed(evt);
            }
        });
        rowPanel2.add(divide);

        mainPanel.add(rowPanel2);

        rowPanel3.setBackground(new java.awt.Color(0, 0, 0));
        rowPanel3.setPreferredSize(new java.awt.Dimension(250, 31));
        rowPanel3.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        digit4.setBackground(new java.awt.Color(102, 102, 102));
        digit4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit4.setForeground(new java.awt.Color(255, 255, 255));
        digit4.setText("4");
        digit4.setBorder(null);
        digit4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel3.add(digit4);

        digit5.setBackground(new java.awt.Color(102, 102, 102));
        digit5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit5.setForeground(new java.awt.Color(255, 255, 255));
        digit5.setText("5");
        digit5.setBorder(null);
        digit5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel3.add(digit5);

        digit6.setBackground(new java.awt.Color(102, 102, 102));
        digit6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit6.setForeground(new java.awt.Color(255, 255, 255));
        digit6.setText("6");
        digit6.setBorder(null);
        digit6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel3.add(digit6);

        times.setBackground(new java.awt.Color(102, 102, 102));
        times.setForeground(new java.awt.Color(255, 255, 255));
        times.setText("*");
        times.setBorder(null);
        times.setMaximumSize(new java.awt.Dimension(75, 31));
        times.setMinimumSize(new java.awt.Dimension(75, 31));
        times.setPreferredSize(new java.awt.Dimension(75, 31));
        times.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opActionPerformed(evt);
            }
        });
        rowPanel3.add(times);

        mainPanel.add(rowPanel3);

        rowPanel4.setBackground(new java.awt.Color(0, 0, 0));
        rowPanel4.setPreferredSize(new java.awt.Dimension(250, 31));
        rowPanel4.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        digit1.setBackground(new java.awt.Color(102, 102, 102));
        digit1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit1.setForeground(new java.awt.Color(255, 255, 255));
        digit1.setText("1");
        digit1.setBorder(null);
        digit1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel4.add(digit1);

        digit2.setBackground(new java.awt.Color(102, 102, 102));
        digit2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit2.setForeground(new java.awt.Color(255, 255, 255));
        digit2.setText("2");
        digit2.setBorder(null);
        digit2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel4.add(digit2);

        digit3.setBackground(new java.awt.Color(102, 102, 102));
        digit3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit3.setForeground(new java.awt.Color(255, 255, 255));
        digit3.setText("3");
        digit3.setBorder(null);
        digit3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel4.add(digit3);

        minus.setBackground(new java.awt.Color(102, 102, 102));
        minus.setForeground(new java.awt.Color(255, 255, 255));
        minus.setText("-");
        minus.setBorder(null);
        minus.setMaximumSize(new java.awt.Dimension(75, 31));
        minus.setMinimumSize(new java.awt.Dimension(75, 31));
        minus.setPreferredSize(new java.awt.Dimension(75, 31));
        minus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opActionPerformed(evt);
            }
        });
        rowPanel4.add(minus);

        mainPanel.add(rowPanel4);

        rowPanel5.setBackground(new java.awt.Color(0, 0, 0));
        rowPanel5.setPreferredSize(new java.awt.Dimension(250, 31));
        rowPanel5.setLayout(new java.awt.GridLayout(1, 0, 3, 0));

        digit0.setBackground(new java.awt.Color(102, 102, 102));
        digit0.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        digit0.setForeground(new java.awt.Color(255, 255, 255));
        digit0.setText("0");
        digit0.setBorder(null);
        digit0.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel5.add(digit0);

        decimal.setBackground(new java.awt.Color(102, 102, 102));
        decimal.setForeground(new java.awt.Color(255, 255, 255));
        decimal.setText(".");
        decimal.setBorder(null);
        decimal.setMaximumSize(new java.awt.Dimension(75, 31));
        decimal.setMinimumSize(new java.awt.Dimension(75, 31));
        decimal.setPreferredSize(new java.awt.Dimension(75, 31));
        decimal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                digitActionPerformed(evt);
            }
        });
        rowPanel5.add(decimal);

        equals.setBackground(new java.awt.Color(102, 102, 102));
        equals.setForeground(new java.awt.Color(255, 255, 255));
        equals.setText("=");
        equals.setBorder(null);
        equals.setMaximumSize(new java.awt.Dimension(75, 31));
        equals.setMinimumSize(new java.awt.Dimension(75, 31));
        equals.setPreferredSize(new java.awt.Dimension(75, 31));
        equals.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opActionPerformed(evt);
            }
        });
        rowPanel5.add(equals);

        plus.setBackground(new java.awt.Color(102, 102, 102));
        plus.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.setToolTipText("Completes current calculation");
        plus.setBorder(null);
        plus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                opActionPerformed(evt);
            }
        });
        rowPanel5.add(plus);

        mainPanel.add(rowPanel5);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Clears display and resets calculator
     */
    private void clear() {
        entering = false;
        result = 0;
        display.setText("0.0");
        operator = '+';
    }
    
    // Returns the inverse of a passed value. For example, passing 10 would result
    // in -10 being returned. This is achieved simply by multiplying by -1.
    private float posNeg(float i)
    {
        if (i == 0)
            return 0;
        else
            return i *= -1; 
    }
    
    // Returns the passed value divided by 100.
    private float percentage(float i)
    {
        return i / 100;
    }

    /**
     * Handler for digit buttons
     *
     * @param evt the ActionEvent
     */
    private void digitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitActionPerformed
        if (!entering) {
            display.setText("");
        }
        display.setText(display.getText() + evt.getActionCommand().charAt(0));
        entering = true;
    }//GEN-LAST:event_digitActionPerformed

    /**
     * Handler for operator buttons
     *
     * @param evt the ActionEvent
     */
    private void opActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opActionPerformed
        float operand = java.lang.Float.parseFloat(display.getText());
        switch (operator) {
            case '+':
                result += operand;
                break;
            case '-':
                result -= operand;
                break;
            case '*':
                result *= operand;
                break;
            case '/':
                result /= operand;
                break;
        }
        display.setText(String.valueOf(result));
        entering = false;
        operator = evt.getActionCommand().charAt(0);
}//GEN-LAST:event_opActionPerformed

    private void ceActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ceActionPerformed
    {//GEN-HEADEREND:event_ceActionPerformed
        clear();
    }//GEN-LAST:event_ceActionPerformed

    private void plusminusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_plusminusActionPerformed
    {//GEN-HEADEREND:event_plusminusActionPerformed
        display.setText(String.valueOf(posNeg(java.lang.Float.parseFloat(display.getText()))));
    }//GEN-LAST:event_plusminusActionPerformed

    private void percentActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_percentActionPerformed
    {//GEN-HEADEREND:event_percentActionPerformed
        display.setText(String.valueOf(percentage(java.lang.Float.parseFloat(display.getText()))));// TODO add your handling code here:
    }//GEN-LAST:event_percentActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized
        // If the window is resized to larger than 500x500px, all fonts are
        // increased (buttons and display label).
        if (evt.getComponent().getHeight() > 500 && evt.getComponent().getWidth() > 500)
        {
            digit1.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit2.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit3.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit4.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit5.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit6.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit7.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit8.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit9.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            digit0.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            ce.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            decimal.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            divide.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            minus.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            plus.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            percent.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            plusminus.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            equals.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            times.setFont(new java.awt.Font("Lucida Grande", 0, 30));
            display.setFont(new java.awt.Font("Lucida Grande", 0, 54));
        }
        
        // Once the window is resized back to less than 500x500px, all fonts
        // are reset to their original size.
        else if (evt.getComponent().getHeight() < 500 && evt.getComponent().getWidth() < 500)
        {
            digit1.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit2.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit3.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit4.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit5.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit6.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit7.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit8.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit9.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            digit0.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            ce.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            decimal.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            divide.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            minus.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            plus.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            percent.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            plusminus.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            equals.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            times.setFont(new java.awt.Font("Lucida Grande", 0, 18));
            display.setFont(new java.awt.Font("Lucida Grande", 0, 36));
        }
    }//GEN-LAST:event_formComponentResized
    private boolean entering;
    private float result;
    private char operator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ce;
    private javax.swing.JButton decimal;
    private javax.swing.JButton digit0;
    private javax.swing.JButton digit1;
    private javax.swing.JButton digit2;
    private javax.swing.JButton digit3;
    private javax.swing.JButton digit4;
    private javax.swing.JButton digit5;
    private javax.swing.JButton digit6;
    private javax.swing.JButton digit7;
    private javax.swing.JButton digit8;
    private javax.swing.JButton digit9;
    private javax.swing.JLabel display;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton divide;
    private javax.swing.JButton equals;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton minus;
    private javax.swing.JButton percent;
    private javax.swing.JButton plus;
    private javax.swing.JButton plusminus;
    private javax.swing.JPanel rowPanel1;
    private javax.swing.JPanel rowPanel2;
    private javax.swing.JPanel rowPanel3;
    private javax.swing.JPanel rowPanel4;
    private javax.swing.JPanel rowPanel5;
    private javax.swing.JButton times;
    // End of variables declaration//GEN-END:variables

}
